{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "332f1a8e-6418-4e27-b53d-6c399af9585e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<>:30: SyntaxWarning: invalid escape sequence '\\]'\n",
      "<>:30: SyntaxWarning: invalid escape sequence '\\]'\n",
      "/var/folders/gc/r_sfkfvx6fd1m6n4q2vc27dm0000gn/T/ipykernel_78511/2109635326.py:30: SyntaxWarning: invalid escape sequence '\\]'\n",
      "  \"\"\"\n"
     ]
    }
   ],
   "source": [
    "import string\n",
    "import random\n",
    "\n",
    "def check_min_length(password: str, min_len: int = 8) -> bool:\n",
    "    \"\"\"Prüft, ob password mindestens min_len Zeichen hat.\"\"\"\n",
    "    return len(password) >= min_len\n",
    "\n",
    "def has_uppercase(password: str) -> bool:\n",
    "    \"\"\"Prüft, ob password mindestens einen Großbuchstaben enthält.\"\"\"\n",
    "    for ch in password:\n",
    "        if ch.isupper():\n",
    "            return True\n",
    "    return False\n",
    "\n",
    "def has_lowercase(password: str) -> bool:\n",
    "    \"\"\"Prüft, ob password mindestens einen Kleinbuchstaben enthält.\"\"\"\n",
    "    for ch in password:\n",
    "        if ch.islower():\n",
    "            return True\n",
    "    return False\n",
    "\n",
    "def has_digit(password: str) -> bool:\n",
    "    \"\"\"Prüft, ob password mindestens eine Ziffer enthält.\"\"\"\n",
    "    for ch in password:\n",
    "        if ch.isdigit():\n",
    "            return True\n",
    "    return False\n",
    "\n",
    "def has_special_char(password: str, special_chars: str = string.punctuation) -> bool:\n",
    "    \"\"\"\n",
    "    Prüft, ob password mindestens ein Sonderzeichen enthält.\n",
    "    Default special_chars ist string.punctuation (!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~).\n",
    "    \"\"\"\n",
    "    for ch in password:\n",
    "        if ch in special_chars:\n",
    "            return True\n",
    "    return False\n",
    "\n",
    "def validate_password(password: str) -> dict:\n",
    "    \"\"\"\n",
    "    Ruft alle Einzelprüfungen auf und liefert ein Dictionary mit Ergebnissen.\n",
    "    Struktur:\n",
    "    \"\"\"\n",
    "    results = {\n",
    "        'check_min_len': check_min_length(password),\n",
    "        'has_upper': has_uppercase(password),\n",
    "        'has_lower': has_lowercase(password),\n",
    "        'has_digit': has_digit(password),\n",
    "        'has_special_char': has_special_char(password)\n",
    "    }\n",
    "\n",
    "    \n",
    "    results['is_valid'] = all(results.values())\n",
    "    return results\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6b9a7f79-a2c5-45c3-99e6-b497d6830365",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
